1) Importe o numpy como “np” e imprima o número da versão.

In [ ]:
import numpy as np
print(np.__version__)

2) Crie um array 1D com números de 0 a 9.

In [ ]:
import numpy as np
a = np.arange(10)
print(a)


3) Crie uma matriz booleana numpy 3×3 com ‘True’.

In [ ]:
import numpy as np
a = np.full((3,3), True)
print(a)

4) Exiba o array da questão 2 com todos os números ímpares substituídos por -1 sem alterar o array.

In [ ]:
import numpy as np
a = np.arange(10)
a[a % 2 == 1] = -1
print(a)

5) Crie 3 matrizes 200 x 200, cada uma com valores aleatórios entre 0 e 255. Junte as 3 matrizes de modo
que uma matriz resultante (200 x200 x 3) seja criada, então exiba como uma imagem utilizando o opencv.

In [ ]:
import cv2
import numpy as np


a = np.random.randint(0, 256, (200,200))
b = np.random.randint(0, 256, (200,200))
c = np.random.randint(0, 256, (200,200))

img = np.dstack((a, b, c))

cv2.imshow('',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

06) Crie um array bidimensional com numpy (com valores pré-definidos) com M linhas e N colunas e em 
seguida crie um array com N elementos e verifique se existe uma linha do primeiro array que corresponde 
ao segundo array criado.

In [14]:
import numpy as np

a = np.random.randint(0,2, (50, 3))

a2 = np.array([0,1,0])
bingo = 0
existe = False

print(f'ARRAY ORIGINAL : ')
for l in a:
    print(l)
print(f' ARRAY 2: {a2}')

for l in a:
    c = np.intersect1d(l, a2)
    if (c == a2).any():
        existe = True

if existe == True:
   print(f'ARRAY 2 está contido no ARRAY OFICIAL na linha {bingo}.')
else: 
    print('ARRAY 2 NÃO está contido no ARRAY OFICIAL')

ARRAY ORIGINAL : 
[1 0 1]
[1 0 1]
[1 0 1]
[1 0 0]
[1 1 0]
[0 1 0]
[1 1 0]
[0 0 0]
[0 1 0]
[0 1 1]
[1 1 1]
[1 0 0]
[0 1 0]
[1 0 1]
[0 1 0]
[0 0 0]
[1 1 0]
[1 0 1]
[0 0 0]
[0 1 0]
[0 0 0]
[1 0 1]
[1 1 0]
[0 1 0]
[0 0 0]
[1 1 1]
[1 0 1]
[1 1 1]
[1 0 0]
[1 1 1]
[1 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 1 1]
[0 0 1]
[0 1 1]
[0 1 1]
[0 0 0]
[1 1 0]
[0 1 0]
[1 0 0]
[0 1 1]
[1 1 0]
[0 0 0]
[1 0 0]
[1 1 0]
[0 0 0]
[1 1 0]
 ARRAY 2: [0 1 0]


C:\Users\davic\AppData\Local\Temp\ipykernel_105296\2790033227.py:16: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if (c == a2).any():


AttributeError: 'bool' object has no attribute 'any'

7) Crie um array de qualquer dimensão com valores de 1 até 10 e após, altere todos os valores 
pares para o valor 45.

In [ ]:
import numpy as np
import numpy.ma as ma

a = np.random.randint(1,11,(5,3))
print('Array original: ')
for r in a:
    print(r)

a[a % 2 == 0] = 45
print('Resultado: ')
for r in a:
    print(r)

8) Crie um array randômico de tamanho 30 e encontre a média e o desvio padrão.

In [ ]:
import numpy as np

a = np.random.randint(0,1000,30)
media = a.mean()
desvio_padrao = a.std()
print(f'ARRAY:  {a} ')
print(f'MÉDIA: {media:.2f}.')
print(f'DESVIO PADRÃO: {desvio_padrao:.2f}')

9) Crie um array randômico de valores inteiros e faça a ordenação desse array.

In [ ]:
import numpy as np

a = np.random.randint(0,101,40)
o = np.sort(a)
print(f'ARREY ORDENADA: {o}.')

10)Crie um array randômico de valores inteiros, em seguida encontre a moda.

In [ ]:
import numpy as np
from scipy import stats as st

a = np.random.randint(0,30,50)
m = st.mode(a)
print(f'ARRAY: {a}')
print(f'MODA: {m[0]}, que se repetiu {m[1]} vezes.')